vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        notebook_image:
           uri_prefix: /images/notebook
           upload_destination: '%kernel.project_dir%/public/images/notebook'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           delete_on_update: true
           delete_on_remove: true
